version: 1.0.{build}
image: Visual Studio 2019

skip_branch_with_pr: true
skip_tags: true

install:
  - SET JAVA_HOME=C:\Program Files\Java\jdk11
  - SET PATH=%JAVA_HOME%\bin;%PATH%

build_script:
- cmd: >-
    build.cmd update-build-version

    build.cmd upload-rider-artifact --configuration Release --is-rider-host

    build.cmd upload-resharper-artifact --configuration Release

    build.cmd sonar --configuration Release

test: off

cache:
  - '%USERPROFILE%\.sonar\cache'
  - '.gradle -> build.gradle'
