//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyTitle("Resharper.ConfigurationSense")]
[assembly: AssemblyVersion("2017.1.1")]
[assembly: AssemblyFileVersion("2017.1.1")]

